schema_version: 1

context:
  version: "1.4.0"
  python_min: "3.11.0"

package:
  name: geoparquet-io
  version: ${{ version }}

source:
  url: https://github.com/geoparquet/geoparquet-io/archive/v${{ version }}.tar.gz
  sha256: eddfa22589fdecf9d84af4bea18f5f874486aee6526eeade7aa5099bd6d2f432

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - gpio = geoparquet_io:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - click
    - click-plugins
    - pyarrow
    - python-duckdb
    - duckdb =1.5.1
    - pandas
    - fsspec
    - rich
    - pystac
    - jsonschema
    - psutil
    - obstore
    - aiohttp
    - s3fs
    - geoarrow-pyarrow
    - pyproj
    - mercantile
    - httpx
    - owslib
    - requests
    - lxml
    - idna
    - urllib3
    # Not in the metadata.
    - shapely

tests:
  - python:
      imports:
        - geoparquet_io
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - gpio --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Fast I/O and transformation tools for GeoParquet files
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/geoparquet/geoparquet-io

extra:
  recipe-maintainers:
    - hobu
